services:
  web:
    image: codegen-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8032:8032"
    depends_on:
      - mysql-db
  mysql-db:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=codesdb'
      - 'MYSQL_PASSWORD=root'
      - 'MYSQL_ROOT_PASSWORD=root'
      - 'MYSQL_USER=codesdb'
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
