
server:
  port: 8032

spring:
  datasource:
    url: jdbc:mysql://mysql-db:3306/codesdb?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari: 
      maximum-pool-size: 100
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      jdbc:
        batch_size: 10000
      order_inserts: true